[project]
name = "dataone-slack-notifications-dev"
version = "0.1.0"
description = "Development environment with Chalice to deploy the notification service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.90",
    "chalice>=1.31.3",
    "requests>=2.32.3",
]
